#!/bin/bash
# Regenerate macos/app/LangMap.h from Notepad++'s own language table.
#
# Source of truth: ScintillaEditView::_langNameInfoArray in
# PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp, which maps each
# Notepad++ language name to the Lexilla lexer ID it uses on Windows. Deriving
# the table instead of hand-writing it keeps macOS and Windows in sync.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT/PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp"
OUT="$ROOT/macos/app/LangMap.h"

START=$(grep -n '_langNameInfoArray\[L_EXTERNAL + 1\] = {' "$SRC" | head -1 | cut -d: -f1)
[ -n "$START" ] || { echo "error: _langNameInfoArray not found in $SRC" >&2; exit 1; }

PAIRS=$(awk -v s="$START" 'NR>=s && /^\};/{exit} NR>=s' "$SRC" \
  | perl -ne 'print "    {\"$1\", \"$2\"},\n" if /\{L"([^"]*)",\s*L"[^"]*",\s*L"[^"]*",\s*L_[A-Z0-9_]+,\s*"([^"]*)"\}/')

COUNT=$(printf '%s\n' "$PAIRS" | grep -c '{' || true)
[ "$COUNT" -gt 50 ] || { echo "error: extracted only $COUNT entries, refusing to write" >&2; exit 1; }

{
  echo "// Generated by macos/gen_langmap.sh -- do not edit by hand."
  echo "// Source: PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp"
  echo "//         (ScintillaEditView::_langNameInfoArray)"
  echo "//"
  echo "// Maps a Notepad++ language name, as used in langs.model.xml, to the"
  echo "// Lexilla lexer ID Notepad++ drives it with."
  echo
  echo "#pragma once"
  echo
  echo "struct NppLangLexer { const char *langName; const char *lexerID; };"
  echo
  echo "static const NppLangLexer kNppLangLexers[] = {"
  printf '%s\n' "$PAIRS"
  echo "};"
  echo
  echo "static const int kNppLangLexerCount = $COUNT;"
} > "$OUT"

echo "wrote $OUT ($COUNT languages)"
