#!/usr/bin/env python3
"""Generates macos/app/BlowfishTables.h: Blowfish's P-array and four S-boxes,
which are nothing but the fractional part of pi written out in hexadecimal -
eighteen words and then four times 256. Worked out here rather than copied, so
the table has no source but arithmetic.

    python3 macos/gen_blowfish_tables.py
"""
import os

WORDS = 18 + 4 * 256
BITS = WORDS * 32
GUARD = 64


def arctan_inverse(x, one):
    """arctan(1/x) scaled by `one`, by the alternating series."""
    total = term = one // x
    square, n, sign = x * x, 3, -1
    while term:
        term //= square
        total += sign * (term // n)
        n, sign = n + 2, -sign
    return total


def main():
    one = 1 << (BITS + GUARD)
    # Machin: pi/4 = 4 arctan(1/5) - arctan(1/239)
    pi = 4 * (4 * arctan_inverse(5, one) - arctan_inverse(239, one))
    fraction = (pi - 3 * one) >> GUARD
    words = [(fraction >> (BITS - 32 * (i + 1))) & 0xFFFFFFFF for i in range(WORDS)]
    assert words[0] == 0x243F6A88 and words[17] == 0x8979FB1B and words[-1] == 0x3AC372E6, "not pi"

    def rows(values):
        return "\n".join("    " + " ".join(f"0x{v:08x}," for v in values[i:i + 6]) for i in range(0, len(values), 6))

    out = ["// Generated by macos/gen_blowfish_tables.py; do not edit.",
           "// Blowfish's initial subkeys: the hexadecimal digits of pi.",
           "#pragma once", "#include <stdint.h>", "",
           "static const uint32_t kBlowfishP[18] = {", rows(words[:18]), "};", "",
           "static const uint32_t kBlowfishS[4][256] = {"]
    for box in range(4):
        out += ["  {", rows(words[18 + 256 * box: 18 + 256 * (box + 1)]), "  },"]
    out += ["};", ""]
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "app", "BlowfishTables.h")
    open(path, "w").write("\n".join(out))
    print("wrote", path)


if __name__ == "__main__":
    main()
