#!/usr/bin/env python3
"""Regenerate macos/app/CP720Table.h from Python's cp720 codec.

Code page 720 (Arabic DOS) has no converter in CoreFoundation or in the system
iconv, so the mapping is embedded. Python's codec is generated from the Unicode
Consortium's mapping, which makes it a checkable source rather than a hand copy.

    python3 macos/gen_cp720.py <repo-root>
"""
import sys, os

root = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(__file__), '..')

# Bytes 0x00-0x7F must be plain ASCII; assert rather than assume.
for b in range(0x80):
    if bytes([b]).decode('cp720') != chr(b):
        sys.exit(f'error: cp720 byte 0x{b:02X} is not ASCII-identical')

high = []
for b in range(0x80, 0x100):
    ch = bytes([b]).decode('cp720')
    if len(ch) != 1:
        sys.exit(f'error: cp720 byte 0x{b:02X} maps to {len(ch)} characters')
    high.append(ord(ch))

# The mapping must be reversible for a lossless encoder.
seen = {}
for i, cp in enumerate(high):
    b = 0x80 + i
    if cp in seen:
        sys.exit(f'error: U+{cp:04X} reached from both 0x{seen[cp]:02X} and 0x{b:02X}')
    seen[cp] = b

out = [
    '// Generated by macos/gen_cp720.py -- do not edit by hand.',
    '// Source: Python\'s cp720 codec, itself generated from the Unicode',
    '// Consortium mapping for IBM/MS code page 720 (Arabic DOS).',
    '//',
    '// Bytes 0x00-0x7F are ASCII. This table covers 0x80-0xFF.',
    '',
    '#pragma once',
    '',
    'static const unsigned short kCP720High[128] = {',
]
for row in range(0, 128, 8):
    cells = ', '.join(f'0x{cp:04X}' for cp in high[row:row + 8])
    out.append(f'    {cells},   // 0x{0x80 + row:02X}')
out += ['};', '']

path = os.path.join(root, 'macos/app/CP720Table.h')
open(path, 'w').write('\n'.join(out))
print(f'wrote {path} -- 128 high-byte mappings, all reversible')
