import re, sys, os

root = sys.argv[1]
rc = os.path.join(root, 'PowerEditor/src/Notepad_plus.rc')
src = open(rc, encoding='utf-8', errors='replace').read()

m = re.search(r'^IDR_[A-Z0-9_]*MENU\s+MENU\b', src, re.M)
block = src[m.start():] if m else src

stack, rows, depth = [], [], 0
for line in block.splitlines():
    t = line.strip()
    if t == 'BEGIN':
        depth += 1; continue
    if t == 'END':
        depth -= 1
        if stack: stack.pop()
        if depth <= 0: break
        continue
    mp = re.match(r'POPUP\s+"([^"]+)"', t)
    if mp:
        stack.append(mp.group(1).replace('&', '')); continue
    mi = re.match(r'MENUITEM\s+"([^"]+)"\s*,\s*(IDM_[A-Z0-9_]+)', t)
    if mi:
        label = mi.group(1).replace('&', '').split('\\t')[0].strip()
        rows.append((list(stack), label, mi.group(2)))

done = set()
impl = os.path.join(root, 'macos/implemented.txt')
if os.path.exists(impl):
    for line in open(impl):
        line = line.split('#')[0].strip()
        if line:
            done.add(line)

groups = {}
for path, label, cid in rows:
    top = path[0] if path else '(root)'
    groups.setdefault(top, []).append((path[1:], label, cid))

total = len(rows)
total_done = sum(1 for _, _, c in rows if c in done)

out = []
out.append('# Notepad++ feature parity on macOS\n')
out.append('Generated by `macos/gen_features.sh` from the Windows menu resource\n'
           '(`PowerEditor/src/Notepad_plus.rc`), so this list cannot drift from upstream.\n')
out.append(f'**{total_done} of {total} menu commands implemented '
           f'({100.0*total_done/total:.1f}%).**\n')

out.append('## Coverage by menu\n')
out.append('| Menu | Done | Total | |')
out.append('|---|---:|---:|---|')
for top in sorted(groups, key=lambda k: -len(groups[k])):
    items = groups[top]
    d = sum(1 for _, _, c in items if c in done)
    filled = int(round(10.0 * d / len(items)))
    bar = '█' * filled + '·' * (10 - filled)
    out.append(f'| {top} | {d} | {len(items)} | `{bar}` |')
out.append('')

out.append('## Commands\n')
for top in sorted(groups, key=lambda k: -len(groups[k])):
    items = groups[top]
    d = sum(1 for _, _, c in items if c in done)
    out.append(f'### {top} — {d}/{len(items)}\n')
    out.append('| | Command | ID |')
    out.append('|---|---|---|')
    for sub, label, cid in items:
        mark = '✅' if cid in done else '☐'
        name = ' › '.join(sub + [label]) if sub else label
        out.append(f'| {mark} | {name} | `{cid}` |')
    out.append('')

open(os.path.join(root, 'macos/FEATURES.md'), 'w').write('\n'.join(out))
print(f'wrote macos/FEATURES.md — {total_done}/{total} commands ({100.0*total_done/total:.1f}%)')
