#!/usr/bin/env python3
"""The menu commands a macro records as themselves (shortcuts.xml's type 2),
read from the switch at the end of Notepad_plus::command in NppCommands.cpp,
written as names to app/MacroableCommands.h."""
import os, re
here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "..", "PowerEditor", "src", "NppCommands.cpp"), encoding="utf-8", errors="replace").read()
start = src.rindex("if (_recordingMacro)")
block = src[start:]
names, pending = [], []
for line in block.splitlines():
    m = re.match(r"\s*case (IDM_\w+)\s*:", line)
    if m:
        pending.append(m.group(1))
        continue
    if "_macro.push_back(recordedMacroStep(id))" in line:
        names += pending
        pending = []
    elif re.match(r"\s*break;", line):
        pending = []
names = sorted(set(names))
with open(os.path.join(here, "app", "MacroableCommands.h"), "w") as out:
    out.write("// Generated by macos/gen_macroable.py from NppCommands.cpp; do not edit.\n")
    out.write("// Menu commands recorded into a macro by their id.\n#pragma once\n")
    out.write("static const char *const kNppMacroableCommands[] = {\n")
    for n in names:
        out.write(f'    "{n}",\n')
    out.write("};\n")
    out.write("static const int kNppMacroableCommandCount = (int)(sizeof(kNppMacroableCommands) / sizeof(kNppMacroableCommands[0]));\n")
print(len(names), "recordable commands")
