import re, sys, os
root = sys.argv[1]
src = open(os.path.join(root, 'PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp'),
           encoding='utf-8', errors='replace').read()
i = src.index('_langNameInfoArray[L_EXTERNAL + 1] = {')
rows = re.findall(r'\{L"([^"]*)",\s*L"[^"]*",\s*L"[^"]*",\s*(L_[A-Z0-9_]+),\s*"([^"]*)"\}', src[i:])
if len(rows) < 50:
    sys.exit(f'error: extracted only {len(rows)} languages, refusing to write')

menu_src = open(os.path.join(root, 'PowerEditor/src/Notepad_plus.rc'),
                encoding='utf-8', errors='replace').read()
menu_ids = set(re.findall(r'IDM_LANG_[A-Z0-9_]+', menu_src))

out = ['// Generated by macos/gen_langmap.sh -- do not edit by hand.',
       '// Source: PowerEditor/src/ScintillaComponent/ScintillaEditView.cpp',
       '//         (ScintillaEditView::_langNameInfoArray)',
       '//',
       '// langName : as used in langs.model.xml',
       '// lexerID  : Lexilla lexer Notepad++ drives the language with',
       '// menuID   : Language-menu command, empty when upstream has no menu entry',
       '', '#pragma once', '',
       'struct NppLangLexer { const char *langName; const char *lexerID; const char *menuID; };',
       '', 'static const NppLangLexer kNppLangLexers[] = {']

mapped = 0
for name, enum, lexer in rows:
    idm = 'IDM_LANG_' + enum[2:]
    if idm not in menu_ids:
        idm = ''
    else:
        mapped += 1
    out.append(f'    {{"{name}", "{lexer}", "{idm}"}},')
out += ['};', '', f'static const int kNppLangLexerCount = {len(rows)};', '']

open(os.path.join(root, 'macos/app/LangMap.h'), 'w').write('\n'.join(out))
print(f'wrote macos/app/LangMap.h -- {len(rows)} languages, {mapped} with a menu command')
