#!/usr/bin/env python3
"""Writes the reference the encoding test checks against.

The old test round-tripped the string "probe 123" through each character set.
That is pure ASCII, so it round-trips through all of them, and a code page
wired to the wrong encoding would have passed. What is needed is ground truth:
what each byte actually means in each code page.

Python ships codecs for every character set Notepad++ offers, so the reference
is taken from there rather than typed out.

    python3 gen_encoding_reference.py       # run from the macos directory

It writes resources/encoding-reference.txt, one line per code page:

    <code page> <tab> <byte as two hex digits> <tab> <code point as hex>

Only the bytes from 0x80 up are listed -- below that every one of these sets
agrees with ASCII. A byte the code page leaves undefined is skipped. Code pages
that are not one byte per character are skipped entirely; they are covered by
their own round-trip tests.
"""

import codecs
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SOURCE = os.path.join(HERE, "app", "EncodingCommands.mm")
OUT = os.path.join(HERE, "resources", "encoding-reference.txt")
HEADER = os.path.join(HERE, "app", "CodePageTables.h")

# The Windows code page numbers Notepad++ uses, and what Python calls them.
ALIASES = {
    28591: "latin_1", 28592: "iso8859_2", 28593: "iso8859_3", 28594: "iso8859_4",
    28595: "iso8859_5", 28596: "iso8859_6", 28597: "iso8859_7", 28598: "iso8859_8",
    28599: "iso8859_9", 28603: "iso8859_13", 28604: "iso8859_14", 28605: "iso8859_15",
    20866: "koi8_r", 21866: "koi8_u", 10007: "mac_cyrillic", 51949: "euc_kr",
}


def codec_for(codepage):
    for name in (ALIASES.get(codepage), "cp%d" % codepage):
        if not name:
            continue
        try:
            return codecs.lookup(name)
        except LookupError:
            pass
    return None


def main():
    text = open(SOURCE, encoding="utf-8", errors="replace").read()
    codepages = []
    for match in re.finditer(r'\{"(IDM_FORMAT_\w+)",[^}]*?,\s*(\d+)\}', text):
        codepages.append(int(match.group(2)))

    lines = []
    tables = {}
    covered = skipped = 0
    # A lead byte of a double-byte set means nothing on its own; the
    # meanings listed here are for the one-byte sets only.
    double_byte = {932, 936, 949, 950}
    for codepage in sorted(set(codepages) - double_byte):
        codec = codec_for(codepage)
        if codec is None:
            skipped += 1
            continue

        rows = []
        multibyte = False
        for byte in range(0x80, 0x100):
            try:
                decoded = codec.decode(bytes([byte]), "strict")[0]
            except (UnicodeDecodeError, UnicodeError):
                # Either undefined, or the first half of a multi-byte sequence.
                continue
            if len(decoded) != 1:
                multibyte = True
                break
            rows.append((byte, ord(decoded)))

        # A set where almost nothing decodes on its own is not one byte per
        # character; those are left to the round-trip tests.
        if multibyte or len(rows) < 32:
            skipped += 1
            continue

        covered += 1
        table = [0xFFFF] * 128
        for byte, point in rows:
            lines.append("%d\t%02X\t%04X" % (codepage, byte, point))
            table[byte - 0x80] = point
        tables[codepage] = table

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as handle:
        handle.write("# Generated by gen_encoding_reference.py from Python's own codecs.\n")
        handle.write("# code page <tab> byte <tab> code point\n")
        handle.write("\n".join(lines) + "\n")

    write_header(tables)
    print("%d code pages, %d byte mappings (%d not single byte, skipped)"
          % (covered, len(lines), skipped))


def write_header(tables):
    """Emits the tables the editor decodes with.

    macOS has converters for most of these, but they do not always agree with
    Windows -- its Icelandic table is another code page's entirely, and its
    Arabic one has eight letters missing -- so the editor uses these instead and
    matches Notepad++ byte for byte.
    """
    out = ["// Generated by gen_encoding_reference.py. Do not edit.",
           "//",
           "// One entry per byte from 0x80 up, for every code page that is one",
           "// byte per character. 0xFFFF means the code page leaves that byte",
           "// undefined. Taken from Python's codecs, which agree with Windows.",
           "#pragma once",
           "#include <stdint.h>",
           "",
           "typedef struct { unsigned int codepage; const uint16_t *high; } NppCodePageTable;",
           ""]
    for codepage in sorted(tables):
        values = ", ".join("0x%04X" % v for v in tables[codepage])
        out.append("static const uint16_t kNppCP%d[128] = { %s };" % (codepage, values))
    out.append("")
    out.append("static const NppCodePageTable kNppCodePageTables[] = {")
    for codepage in sorted(tables):
        out.append("    { %d, kNppCP%d }," % (codepage, codepage))
    out.append("};")
    out.append("")
    out.append("static const int kNppCodePageTableCount = %d;" % len(tables))
    out.append("")
    with open(HEADER, "w") as handle:
        handle.write("\n".join(out))


if __name__ == "__main__":
    main()
